documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'Documentation/**'
          - 'README.md'
          - 'CONTRIBUTING.md'
          - 'CHANGELOG.md'
          - 'SECURITY.md'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'Tests/**'
          - 'Build/phpunit.xml'
          - 'Build/FunctionalTests.xml'
          - 'infection.json5'
          - 'phpat.neon'

security:
  - changed-files:
      - any-glob-to-any-file:
          - 'Classes/Crypto/**'
          - 'Classes/Security/**'
          - 'Classes/Audit/**'
          - '.gitleaks.toml'

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - 'Configuration/**'
          - 'ext_localconf.php'
          - 'ext_emconf.php'
          - 'ext_conf_template.txt'
          - 'composer.json'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - 'Makefile'
          - 'phpstan.neon'
          - 'rector.php'
          - 'fractor.php'
          - '.php-cs-fixer.dist.php'
          - 'codecov.yml'

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'Resources/Public/**'
          - 'Resources/Private/Templates/**'
          - 'Resources/Private/Language/**'

domain:
  - changed-files:
      - any-glob-to-any-file:
          - 'Classes/Domain/**'
          - 'Classes/Service/**'
          - 'ext_tables.sql'
